# Generated by Django 4.0.3 on 2022-03-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='LsgBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('Gram Panchayat', 'Gram panchayat'), ('Municipality', 'Municipality')], max_length=80)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.district')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Rajasthan', 'Rajasthan'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Karnataka', 'karnataka'), ('Maharastra', 'Maharastra')], max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('number', models.IntegerField()),
                ('lsg_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.lsgbody')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PHC', 'PHC'), ('CHC', 'CHC')], max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.ward')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.state'),
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('district_admin', 'district_admin'), ('primary_nurse', 'primary_nurse'), ('secondary_nurse', 'secondary_nurse')], max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.district')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
