# Generated by Django 4.0.3 on 2022-03-02 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='district',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.district'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='facility',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.facility'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('district_admin', 'district_admin'), ('primary_nurse', 'primary_nurse'), ('secondary_nurse', 'secondary_nurse')], default=('district_admin', 'district_admin'), max_length=80),
        ),
    ]
