# Generated by Django 4.0.3 on 2022-03-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_alter_appuser_district_alter_appuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
