# Generated by Django 4.0.3 on 2022-03-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_alter_appuser_district_alter_appuser_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
