# Generated by Django 4.0.3 on 2022-03-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_appuser_groups_appuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
