# Generated by Django 4.0.3 on 2022-03-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0008_auto_20220303_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lsgbody',
            old_name='state',
            new_name='district',
        ),
        migrations.AddField(
            model_name='lsgbody',
            name='lsg_body_code',
            field=models.CharField(default=50, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lsgbody',
            name='kind',
            field=models.CharField(choices=[(1, 'Grama Panchayath'), (2, 'Block Panchayath'), (3, 'District Panchayath'), (4, 'Nagar Panchayath'), (10, 'Municipality'), (20, 'Corporation'), (50, 'Others')], max_length=80),
        ),
    ]
