# Generated by Django 4.0.3 on 2022-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0010_alter_lsgbody_lsg_body_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsgbody',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Grama Panchayath'), (2, 'Block Panchayath'), (3, 'District Panchayath'), (4, 'Nagar Panchayath'), (10, 'Municipality'), (20, 'Corporation'), (50, 'Others')]),
        ),
        migrations.AlterField(
            model_name='lsgbody',
            name='lsg_body_code',
            field=models.CharField(max_length=80),
        ),
    ]
