# Generated by Django 4.0.1 on 2022-03-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_famildetail_familydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitschedule',
            name='visit_completed',
            field=models.BooleanField(default=False),
        ),
    ]
