# Generated by Django 4.0.1 on 2022-03-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='expired_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='landmark',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
