# Generated by Django 4.0.3 on 2022-03-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palliative_phase', models.CharField(max_length=80)),
                ('blood_pressure', models.CharField(max_length=80)),
                ('pulse', models.CharField(max_length=80)),
                ('general_random_blood_sugar', models.CharField(max_length=80)),
                ('personal_hygiene', models.CharField(max_length=80)),
                ('mouth_hygiene', models.CharField(max_length=80)),
                ('pubic_hygiene', models.CharField(max_length=80)),
                ('systemic_examination', models.CharField(max_length=80)),
                ('patient_at_peace', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('symptoms', models.CharField(max_length=80)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.appuser')),
            ],
        ),
    ]
